set YYYYMMDD=%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%
mkdir Backup-%YYYYMMDD%
cd /d [INSERT TEAMSPEAK SERVER DIRECTORY]
copy ts3server.sqlitedb [INSERT BACKUP DIRECTORY HERE]\Backup-%YYYYMMDD%\
start [INSERT TEAMSPEAK SERVER DIRECTORY]\ts3server.exe
exit